language: node_js
sudo: false
node_js:
  - stable
install:
  - yarn install
script:
  - yarn test:unit
  - yarn dist
  - yarn build
  - chmod u+x deploy.sh
  - bash ./deploy.sh
after_script:
  - yarn install codecov && codecov
